// GENERAL ACTIONS
export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_COURSE = "FETCH_COURSE";
export const ADD_COURSE = "ADD_COURSE"
export const DELETE_COURSE = "DELETE_COURSE"
export const FETCH_TESTS = "FETCH_TESTS";
export const FETCH_TEST = "FETCH_TEST";
export const ADD_TEST = "ADD_TEST"
export const DELETE_TEST = "DELETE_TEST"
export const SEND_CODE = "SEND_CODE"

//STUDENTS ACTION TYPES
export const FETCH_STUDENTS = "FETCH_STUDENTS";
export const FETCH_STUDENT = "FETCH_STUDENT";
export const ADD_STUDENT = "ADD_STUDENT";
export const ADD_STUDENT_FAILED = "ADD_STUDENT_FAILED";
export const ADD_STUDENT_MOMO = "ADD_STUDENT_MOMO"
export const DELETE_STUDENT_MOMO = "DELETE_STUDENT_MOMO"
export const DELETE_STUDENT = "DELETE_STUDENT";
export const STUDENT_LOADING = "STUDENT_LOADING";
export const STUDENT_LOADED = "STUDENT_LOADED";
export const STUDENTS_LOADING = "STUDENTS_LOADING";
export const STUDENTS_LOADED = "STUDENTS_LOADED";

//CREATORS ACTION TYPES
export const FETCH_CREATORS = "FETCH_CREATORS";
export const ADD_CREATOR = "ADD_CREATOR";
export const ADD_CREATOR_FAILED = "ADD_CREATOR_FAILED";
export const ADD_CREATOR_MOMO = "ADD_CREATOR_MOMO"
export const DELETE_CREATOR_MOMO = "DELETE_CREATOR_MOMO"
export const DELETE_CREATOR = "DELETE_CREATOR";
export const CREATOR_LOADING = "CREATOR_LOADING";
export const NEXT = "NEXT";
export const CUSTOMER_LOADING = "CUSTOMER_LOADING";
export const CREATOR_LOADED = "CREATOR_LOADED";
export const CREATORS_LOADING = "CREATORS_LOADING";
export const CREATORS_LOADED = "CREATORS_LOADED";
export const CUSTOMER_LOADED = "CUSTOMER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";


//ADMINS ACTION TYPES
export const DELETE_ADMIN = "DELETE_ADMIN";
export const ADD_ADMIN = "ADD_ADMIN";
export const FETCH_ADMINS = "FETCH_ADMINS";
export const ADD_ADMIN_MOMO = "ADD_ADMIN_MOMO"
export const DELETE_ADMIN_MOMO = "DELETE_ADMIN_MOMO"
export const ADMINS_LOADING = "ADMINS_LOADING";
export const ADMIN_LOADING = "ADMIN_LOADING";
export const ADMIN_LOADED = "ADMIN_LOADED";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PIN = "CHANGE_PIN";
export const CHANGE_FAIL = "CHANGE_FAIL";
export const CHANGE_STATUS = "CHANGE_STATUS";
export const FAILED = "FAILED";

